jvjsozknvkskznbbcj

diff --git a/bin/cdpatch b/bin/cdpatch
--- a/bin/cdpatch
+++ b/bin/cdpatch
@@ -1,1 +1,1 @@
-echo "$1" | grep https && ( curl $1.patch | patch -p1 --dry-run  ) || echo wrong input
+echo "$1" | grep https && ( curl $1.patch | patch -p1 --dry-run  ) || echo failed
diff --git a/bin/cpatch b/bin/cpatch
--- a/bin/cpatch
+++ b/bin/cpatch
@@ -1,1 +1,1 @@
-echo "$1" | grep https && ( curl $1.patch | patch -p1 --no-backup ) || echo wrong input
+echo "$1" | grep https && ( curl $1.patch | patch -p1 --no-backup ) || echo failed
