q
Signed-off-by: fukiame <fukiame@proton.me>

diff --git a/bin/cdpatch b/bin/cdpatch
--- a/bin/cdpatch
+++ b/bin/cdpatch
@@ -1,1 +1,5 @@
-echo "$1" | grep https && ( curl $1.patch | sed "$2" | patch -p1 --dry-run ) || echo failed
+echo "$1" | grep https || echo failed
+[ -n "$KANG_SED" ] && sedarg="$KANG_SED" || sedarg="$2"
+(
+  curl "$1.patch" | sed "$sedarg" | patch -p1 --dry-run
+) || echo failed
